[.lightbg,background-video="videos/sky.mov",background-video-loop="true",background-opacity="0.7"]
== Delegate work

* There might be some(one|thing) or layer that can do it.
* Move work to another layer.
* Most of the CRUD code can be done by the database.

[.notes]
--
* Of many applications, 90 to 95 % of the operations is CRUD. Most of it (including translating to and from json) can be done by the database.
--

=== Example JSON

* The database can produce a JSON result, if nicely asked.
* The database can also accept JSON.
* avoid useless transformations.

[.notes]
--
* Many database can produce and process json from and to table form.
* In a rest application, that avoids object to json on json to object transformations.
--

=== Example JSON cont'd

* Role of middle-ware is either short-circuit db and front-end

[.notes]
--
* the middle-ware's role is reduced to transforming to and from formats the database can't provide, but be aware of
useless transformations, e.g. from db to pojo to json if the database can do json already.
* If the front end consumes json, then have the database produce it.
--

=== Benefits of reduced work

* if a lot is done in the database layer, choosing another language for middle-ware of front-end becomes trivial.

[.notes]
--
* The smaller a component, the easier it is to replace.
--
