[.lightbg,background-video="videos/woman-study.mp4",background-video-loop="true",background-opacity="0.7"]
== Read more code

[.lightbg,background-video="videos/woman-study.mp4",background-video-loop="true",background-opacity="0.7"]
=== The importance of reading code and readability.

[quote, Martin Fowler, Refactoring]
Any fool can write code that a computer can understand. +
Good programmers write code that humans can understand.

[.notes]
--
* a method/class/package a day keeps the architect away.
* Visit code exhibits (good example open source).
* The naming problem. Good type (class) and method names are a boon to readability.
--

=== Collect good examples

[.notes]
--
* even home brew, if the can withstand some scrutiny
*  and present to the students to study, maybe as part of a bigger exercise. Reading a lot makes a better writer, also for code.
--

=== Homework should not be just writing programs

[.notes]
--
* Good code is understandable code, by virtue of the names used and the easy to understand constructs.
* Another reason to avoid *code duplication or copy and waste*: all that copied code has to be read too, which is
  both boring and a waste of reading time.
* Review code, in particular or readability, not just on functional correctness.
--
